env:
  es6: true
  node: true
extends: standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - args: none
  comma-dangle:
    - error
    - always-multiline
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-unreachable: off
  space-before-function-paren:
    - error
    - never
  no-console: error
  array-bracket-spacing:
    - error
    - always
  dot-notation: off
